config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    resources :products
    get "/home" , to: "static_pages#home"
    devise_for :users
    resources :users, only: [:index, :show, :destroy]
    namespace :admin do
      root to: "users#index"
      get "/listcates" , to: "categories#index"
      get "/listproducts" , to: "products#index"
      get "/listorders" , to: "orders#index"
      resources :orders
      resources :categories
      resources :users
      resources :products
    end
    resources :carts
    get "/carts_show", to: "carts#show"
    get "/orders_show", to: "orders#show"
    get "/suggests_show", to: "suggests#show"
    delete "/destroy_cart", to: "carts#destroy"
    delete "/cart_delete_item", to: "carts#cart_delete_item"
    put "/carts_update", to: "carts#cart_update_item"
    get "/checkout", to: "carts#checkout"
    get "/products", to: "products#index"
    get "/about", to: "static_pages#about"
    get "/new_suggests", to: "suggests#index"
    resources :suggests
    resources :orders
    resources :order_details

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_cart, only: [:show, :checkout]

  def create
    check_current_cart params[:product_id]
    if session[:cart]
      @cart_products = Product.select_id_product session[:cart].keys
      if @cart_products
        respond_to do |format|
          format.html{return @cart_products}
          format.js
        end
      end
    end
  end

  def check_current_cart product_id
    if session[:cart]
      if session[:cart].key?(product_id.to_s)
        session[:cart][product_id.to_s] += 1
      else
        session[:cart].store(product_id.to_s, 1)
      end
      flash[:success] = t "flash.cart_add_item"
    else
      session[:cart] = {}
    end
  end

  def show; end

  def checkout; end

  def cart_update_item
    session[:cart][params[:product_id]] = params[:quantity].to_i
    if session[:cart]
      @cart_products = Product.select_id_product session[:cart].keys
      if @cart_products
        respond_to do |format|
          format.html{return @cart_products}
          format.json { render json: @cart_products.to_json }
          format.js
        end
      end
    end
  end

  def cart_delete_item
    session[:cart].delete(params[:product_id].to_s)
    if session[:cart]
      @cart_products = Product.select_id_product session[:cart].keys
      if @cart_products
        respond_to do |format|
          format.html{return @cart_products}
          format.js
        end
      end
    end
  end

  def destroy
    session.delete(:cart)
  end

  private

  def load_cart
    if session[:cart]
      @cart_products = Product.select_id_product session[:cart].keys
      if @cart_products
        respond_to do |format|
          format.html{return @cart_products}
          format.js
        end
      end
    end
    flash[:danger] = t "flash.cart_notfound"
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def quantity_in_carts
    quantity = 0
    session[:cart].each do |index, value|
      quantity += 1
    end
    quantity
  end

  def total_order
    products = Product.select_id_product session[:cart].keys
    total_price_order = 0
    products.each do |item|
      total_price_order += item.price * session[:cart][item.id.to_s]
    end
    total_price_order
  end
end

app/views/carts/_cart_mini.html.erb
<a href= <%= carts_show_path %> class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-shopping-cart"></span>(<%= quantity_in_carts %>) Items<span class="caret"></span></a>
<ul class="dropdown-menu dropdown-cart" role="menu">
 <% cart_products.each do |cart_product|  %>
 <li >
  <span class="item">
    <span class="item-left">
     <%= image_tag cart_product.images[0].picture, alt: cart_product.name, class: "img-responsive image_in_carts" %>
     <span class="item-info">
       <span><%= cart_product.name %></span>
       <span><%= cart_product.price %></span>
     </span>
   </span>
   <span class="item-right">
     <%= link_to "<i class='btn btn-xs btn-danger pull-right'>x</i>".html_safe, cart_delete_item_path(product_id: cart_product.id), remote: true, method: :DELETE %>
   </span>
 </span>
</li>
<%end%>
<li><%= link_to "View Cart", carts_show_path, class: "text-center" %></li>
<li class="divider"></li>
</ul>

app/views/carts/_cart_product.html.erb
<tr>
    <td>
      <div class="row">
        <div class="col-sm-2 hidden-xs"><%= image_tag cart_product.images[0].picture, alt: cart_product.name, class: "img-responsive" %>
        </div>
        <div class="col-sm-10">
          <h4 class="nomargin"><%= cart_product.name %></h4>
          <p><%= cart_product.description %></p>
        </div>
      </div>
    </td>
    <td><%= cart_product.price %></td>
    <td>
      <%= form_tag carts_update_path(product_id: cart_product.id), class: "update_cart_form", remote: true, method: :PUT do %>
        <%= number_field_tag :quantity, session[:cart][cart_product.id.to_s] %></%>
    <td>
      <button type="submit" class="btnCartProduct btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
    </td>
      <% end %>
    </td>
    <td class="text-center"><%= cart_product.price * session[:cart][cart_product.id.to_s]%></td>
    <td class="actions" data-th="">
      <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, cart_delete_item_path(product_id: cart_product.id), remote: true, method: :DELETE%>
    </td>
</tr>

app/views/carts/_checkout_item.html.erb
<% cart_products.each do |cart_product|  %>
<div class="media">
  <%= image_tag cart_product.images[0].picture, alt: cart_product.name, :class => "img-responsive image_in_carts pull-left" %>
  <div class="media-body">
    <p class="font-large"><%= cart_product.name %></p>
    <span class="color-gray your-order-info">Price: <%= cart_product.price %></span>
    <span class="color-gray your-order-info">Qty: <%= session[:cart][cart_product.id.to_s] %></span>
    <span class="color-gray your-order-info">Subtotal: <%= cart_product.price * session[:cart][cart_product.id.to_s]%>
    </span>
  </div>
</div>
<% end %>

app/views/carts/_total.html.erb
<tr>
  <td><a href=<%= root_path %> class="btn btn-warning"><i class="fa fa-angle-left"></i>
    <%= t "carts.index.continue" %></a>
  </td>
  <td colspan="2" class="hidden-xs"></td>
  <td colspan="1" class="hidden-xs"></td>
  <td class="hidden-xs text-center"><%= t "carts.index.total"%><strong><%= total_price_order = total_order %></strong>
  </td>
  <% if(quantity_in_carts > 0) %>
  <td><%= link_to t("carts.index.next"), checkout_path, class: "btn btn-success" %></td>
  <% end %>
</tr>

app/views/carts/cart_delete_item.js.erb
$(".cart_list").html("<%= escape_javascript(render partial: 'cart_product', collection: @cart_products) %>")
$(".cart_total").html("<%= escape_javascript(render 'carts/total')%>")
$(".cart_mini_top").html("<%= escape_javascript(render 'carts/cart_mini', cart_products: @cart_products) %>")

app/views/carts/cart_update_item.js.erb
  $('.btnCartProduct').bind('ajax:success', function(e) {
    $(".cart_list").html("<%= escape_javascript(render partial: 'cart_product', collection: @cart_products) %>");
    $(".cart_total").html("<%= escape_javascript(render 'carts/total')%>");
    $(".cart_mini_top").html("<%= escape_javascript(render 'carts/cart_mini', cart_products: @cart_products) %>");
  });

app/views/carts/checkout.html.erb
<% provide(:title, "checkout") %>
<div id="content">
  <form action="#" method="post" class="beta-form-checkout">
    <h1><%= t "carts.checkout.order" %></h4>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="your-order">
          <div class="your-order-head center"><h5><%= t "carts.checkout.order_detail" %></h5></div>
          <div class="your-order-body" style="padding: 0px 10px">
            <div class="your-order-item">
              <div>
                <!--  one item   -->
                  <%= render "carts/checkout_item", cart_products: @cart_products%>
                <!-- end one item -->
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="your-order-item">
              <div class="pull-left"><p class="your-order-f18"><%= t "carts.checkout.total" %></p></div>
              <div class="pull-right"><h5 class="color-black"><%= total_price_order = total_order %></h5></div>
              <div class="clearfix"></div>
            </div>
          </div>
          <div class="your-order-head"><h5><%= t "carts.checkout.payment" %></h5></div>

          <div class="your-order-body">
            <ul class="payment_methods methods">
              <li class="payment_method_bacs">
                <input id="payment_method_bacs" type="radio" class="input-radio" name="payment_method" value="COD" checked="checked" data-order_button_text="">
                <label for="payment_method_bacs"><%= t "carts.checkout.method" %></label>
                <div class="payment_box payment_method_bacs" style="display: block;">
                  <%= t "carts.checkout.delivery" %>
                </div>
              </li>
            </ul>
          </div>
          <div class="text-center">
            <a class="beta-btn primary" href="/carts_show"><i class="fa fa-chevron-left"></i>Back</a>
             <%= link_to t("carts.index.checkout"), order_details_path(total: total_price_order), method: :POST,class: "beta-btn primary" %>
          </div>
        </div> <!-- .your-order -->
      </div>
    </div>
  </form>
</div> <!-- #content -->

app/views/carts/create.js.erb
$(".cart_mini_top").html("<%= escape_javascript(render 'carts/cart_mini', cart_products: @cart_products) %>")

app/views/carts/show.html.erb
<% provide(:title, t("carts.index.title")) %>
<h1><%= t "carts.index.title" %></h1>
<table id="cart" class="table table-hover table-condensed">
  <thead>
    <tr>
      <th class="display_50"><%= t "carts.index.product" %></th>
      <th class="display_10"><%= t "carts.index.price" %></th>
      <th class="display_10"><%= t "carts.index.quantity" %></th>
      <th class="display_5"></th>
      <th class="display_20 text-center"><%= t "carts.index.subtotal" %></th>
      <th class="display_5"> <%= t "carts.index.action" %> </th>
    </tr>
  </thead>
  <tbody class = "cart_list">
    <%= render partial: "cart_product", collection: @cart_products %>
  </tbody>
  <tfoot class = "cart_total">
    <%= render "carts/total" %>
  </tfoot>
</table>