config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    resources :products
    get "/home" , to: "static_pages#home"
    devise_for :users
    resources :users, only: [:index, :show, :destroy]
    namespace :admin do
      root to: "users#index"
      get "/listcates" , to: "categories#index"
      get "/listproducts" , to: "products#index"
      get "/listorders" , to: "orders#index"
      resources :orders
      resources :categories
      resources :users
      resources :products
    end
    resources :carts
    get "/carts_show", to: "carts#show"
    get "/orders_show", to: "orders#show"
    get "/suggests_show", to: "suggests#show"
    delete "/destroy_cart", to: "carts#destroy"
    delete "/cart_delete_item", to: "carts#cart_delete_item"
    put "/carts_update", to: "carts#cart_update_item"
    get "/checkout", to: "carts#checkout"
    get "/products", to: "products#index"
    get "/about", to: "static_pages#about"
    get "/new_suggests", to: "suggests#index"
    resources :suggests
    resources :orders
    resources :order_details

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/common/admin/_body_admin.html.erb
<!-- body admin -->
<div class="container-fluild">
  <div class="row">
    <!-- vertical menu left body-->
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <div class="nav-side-menu">
        <div class="brand"><%= t"common.admin.body.title" %></div>
        <div class="menu-list">
            <ul id="menu-content">
              <li  data-toggle="collapse" data-target="#user" class="collapsed active">
                <a href="#">
                  <i class="fa fa-users fa-lg"></i><%= t"common.admin.body.users" %><span class="caret"></span>
                </a>
              </li>
              <ul class="sub-menu collapse" id="user">
                <li><i class="fa fa-angle-right"></i>
                  <%=link_to t("common.admin.body.list_user") , admin_root_path %>
                </li>
                <li><i class="fa fa-angle-right"></i>
                  <%=link_to t("common.admin.body.add_user"), new_admin_user_path %>
                </li>
              </ul>
              <li data-toggle="collapse" data-target="#categories" class="collapsed">
                <a href="#">
                  <i class="fa fa-bars"></i><%= t "common.admin.body.cate" %><span class="caret"></span>
                </a>
              </li>
              <ul class="sub-menu collapse" id="categories">
                <li><i class="fa fa-angle-right"></i><%=link_to t("common.admin.body.list_cate"), admin_listcates_path %></li>
                <li><i class="fa fa-angle-right"></i><%=link_to t("common.admin.body.add_cate"), "#" %></li>
              </ul>
              <li data-toggle="collapse" data-target="#product" class="collapsed">
                <a href="#">
                  <i class="fa fa-gift"></i> <%= t "common.admin.body.product" %><span class="caret"></span>
                </a>
              </li>
              <ul class="sub-menu collapse" id="product">
                <li><i class="fa fa-angle-right"></i> <%= link_to t("common.admin.body.list_product"), admin_listproducts_path %></li>
                <li><i class="fa fa-angle-right"></i> <%= link_to t("common.admin.body.add_product"), "#" %></li>
              </ul>
              <li data-toggle="collapse" data-target="#order" class="collapsed">
                <a href=<%= admin_listorders_path %>>
                  <i class="fa fa-cart-plus"></i><%= t("common.admin.body.order") %><span class="arrow"></span>
                </a>
              </li>
            </ul>
        </div>
      </div>
    </div> <!--end vertical menu left body-->
    <!-- right body -->
    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
       <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      <%= yield %>
    </div>
  </div>
</div>

app/views/common/admin/_header_admin.html.erb
<!-- header admin -->
<nav class="navbar fixed-top navbar-default" role="navigation" style="background-color: #23282e">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><i class="fa fa-home"><%= t "common.admin.header.title" %></i></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse fixed-top">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t "common.admin.header.admin" %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to t("common.admin.header.edit"), edit_admin_user_path(current_user) %></li>
            <li><%= link_to t("common.admin.header.log_out"), destroy_user_session_path, method: :delete %></li>
              <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
<!-- end header admin  -->