config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    resources :products
    get "/home" , to: "static_pages#home"
    devise_for :users
    resources :users, only: [:index, :show, :destroy]
    namespace :admin do
      root to: "users#index"
      get "/listcates" , to: "categories#index"
      get "/listproducts" , to: "products#index"
      get "/listorders" , to: "orders#index"
      resources :orders
      resources :categories
      resources :users
      resources :products
    end
    resources :carts
    get "/carts_show", to: "carts#show"
    get "/orders_show", to: "orders#show"
    get "/suggests_show", to: "suggests#show"
    delete "/destroy_cart", to: "carts#destroy"
    delete "/cart_delete_item", to: "carts#cart_delete_item"
    put "/carts_update", to: "carts#cart_update_item"
    get "/checkout", to: "carts#checkout"
    get "/products", to: "products#index"
    get "/about", to: "static_pages#about"
    get "/new_suggests", to: "suggests#index"
    resources :suggests
    resources :orders
    resources :order_details

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :order_details

  scope :join_images, ->{joins :images}
  scope :order_by_name, ->{order name: :DESC}
  scope :select_id_product, ->(id_product){where id: id_product}
  scope :select_cate_product, ->(cate_product){where category_id: cate_product}
  scope :get_cate, ->{joins :order_details}
  scope :starts_with, ->(product_name){ where("name like ?", "#{product_name}%")}

  accepts_nested_attributes_for :images

  scope :search_price, lambda {|price_from, price_to| where("price >= ? AND price <= ?", price_from, price_to)}
  scope :search_from, ->(price_from){where("price >= ?","#{price_from}%")}
  scope :search_to, ->(price_to){where("price <= ?","#{price_to}%")}

  scope :cakes, (lambda do
    select(:id, :name, :price, "images.picture")
    .joins(:category, :images)
    .where(categories: {name: "banh"})
    .order(created_at: :DESC)
    .limit(8)
  end)

  scope :coffees, (lambda do
    select(:id, :name, :price, "images.picture")
    .joins(:category, :images)
    .where(categories: {name: "caphe"})
    .order(created_at: :DESC)
    .limit(8)
  end)

  scope :teas, (lambda do
    select(:id, :name, :price, "images.picture")
    .joins(:category, :images)
    .where(categories: {name: "trasua"})
    .order(created_at: :DESC)
    .limit(8)
  end)

  def self.searchs searchs
    if searchs
      if searchs[:pricefrom].present? && searchs[:priceto].present?
        results = self.search_price(searchs[:pricefrom], searchs[:priceto])
      elsif searchs[:priceto].present?
        result = self.search_to(searchs[:priceto])
      elsif searchs[:pricefrom].present?
        result = self.search_from(searchs[:pricefrom])
      elsif result.present?
        results = results.select_cate_product(searchs[:sltCategory]) if searchs[:sltCategory].present?
      elsif result.blank?
        results= self.select_cate_product(searchs[:sltCategory]) if searchs[:sltCategory].present?
      end
    else
      where(nil)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"

  before_action :load_product, except: [:index, :new, :create]

  def index
    @products = Product.includes(:images).order_by_name.paginate page: params[:page],
      per_page: Settings.products.paginate.per_page
  end

  def new
    @product = Product.new
    @image = @product.images.build
  end

  def create; end

  def edit; end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "flash.update_success"
    else
      flash[:danger] = t "flash.updated_fail"
    end
    redirect_to admin_listproducts_path
  end

  def destroy
    if @product.destroy
      flash[:success] = t "flash.product_delete_success"
    else
      flash[:danger] = t "flash.destroy_fail"
    end
    redirect_to admin_listproducts_path
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    @check_product = OrderDetail.find_by product_id: @product[:id]
    if @check_product
      if @check_product.order.finished?
        return @product
      else
        flash[:danger] = t "flash.product_delete_fail"
        redirect_to admin_listproducts_path
      end
    elsif @check_product.nil?
      return @product
    end
  end

  def product_params
    params.require(:product).permit :name, :price, :description,
      images_attributes: [:id, :product_id, :picture]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show

  def index
    @products = Product.includes(:images).paginate page: params[:page],
      per_page: Settings.products.paginate.per_page
    @q = Product.ransack(params[:q])
    @searchs = @q.result(distinct: true)
    @searchs = @searchs.select_cate_product(params[:sltCategory]) if params[:sltCategory]
    if session[:cart]
      @cart_products = Product.select_id_product session[:cart].keys
      return if @cart_products
    end
  end

  def show
    if @product
      respond_to do |format|
        format.html{return @product}
        format.js
      end
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t "flash.not_found"
    redirect_to root_path
  end

  def search_params
    params.permit :sltCategory, :priceto, :pricefrom
  end
end

app/views/admin/products/_error_messages.html.erb
<% if @product.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.error_messages.contains" %> <%= pluralize(@product.errors.count, t("shared.error_messages.errors")) %>.
    </div>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.price %></td>
  <td><%= image_tag product.images[0].picture.url, alt: product.name, class: "img-responsive image_in_admin" %></td>
  <td><i class="fa fa-edit"></i><%= link_to t("admin.products.index.edit"), edit_admin_product_path(product) %></td>
  <td><i class="fa fa-window-close"></i>
    <%= link_to t("admin.products.index.delete"), [:admin, product], method: :DELETE,
      data: { confirm: t("admin.products.index.delete") } %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide(:title, t("admin.products.edit.title")) %>
<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 center_div">
    <h1><%= t"admin.products.edit.title" %></h1>

    <%= form_for([:admin, @product], html: {multipart: true})  do |f| %>
      <%= render "error_messages" %>

      <%= f.label :name, t("admin.products.edit.name")  %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :price, t("admin.products.edit.price") %>
      <%= f.text_field :price, class: "form-control" %>

      <%= f.label :description, t("admin.products.edit.description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :images, t("admin.products.edit.url") %>
      <%= f.fields_for :images do |p| %>
      <div class="field">
        <%= p.file_field :picture, class: "form-control" %>
      </div>
      <% end %>
      <%= f.submit t("admin.products.edit.button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide(:title, t("admin.products.index.title")) %>
<h1><%= t "admin.products.index.title" %></h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= t "admin.products.index.name" %></th>
      <th scope="col"><%= t "admin.products.index.price" %></th>
      <th scope="col"><%= t "admin.products.index.image" %></th>
      <th scope="col"><%= t "admin.products.index.edit" %></th>
      <th scope="col"><%= t "admin.products.index.delete" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @products %>
  </tbody>
</table>
<%= will_paginate %>