config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    resources :products
    get "/home" , to: "static_pages#home"
    devise_for :users
    resources :users, only: [:index, :show, :destroy]
    namespace :admin do
      root to: "users#index"
      get "/listcates" , to: "categories#index"
      get "/listproducts" , to: "products#index"
      get "/listorders" , to: "orders#index"
      resources :orders
      resources :categories
      resources :users
      resources :products
    end
    resources :carts
    get "/carts_show", to: "carts#show"
    get "/orders_show", to: "orders#show"
    get "/suggests_show", to: "suggests#show"
    delete "/destroy_cart", to: "carts#destroy"
    delete "/cart_delete_item", to: "carts#cart_delete_item"
    put "/carts_update", to: "carts#cart_update_item"
    get "/checkout", to: "carts#checkout"
    get "/products", to: "products#index"
    get "/about", to: "static_pages#about"
    get "/new_suggests", to: "suggests#index"
    resources :suggests
    resources :orders
    resources :order_details

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :order_details

  scope :join_images, ->{joins :images}
  scope :order_by_name, ->{order name: :DESC}
  scope :select_id_product, ->(id_product){where id: id_product}
  scope :select_cate_product, ->(cate_product){where category_id: cate_product}
  scope :get_cate, ->{joins :order_details}
  scope :starts_with, ->(product_name){ where("name like ?", "#{product_name}%")}

  accepts_nested_attributes_for :images

  scope :search_price, lambda {|price_from, price_to| where("price >= ? AND price <= ?", price_from, price_to)}
  scope :search_from, ->(price_from){where("price >= ?","#{price_from}%")}
  scope :search_to, ->(price_to){where("price <= ?","#{price_to}%")}

  scope :cakes, (lambda do
    select(:id, :name, :price, "images.picture")
    .joins(:category, :images)
    .where(categories: {name: "banh"})
    .order(created_at: :DESC)
    .limit(8)
  end)

  scope :coffees, (lambda do
    select(:id, :name, :price, "images.picture")
    .joins(:category, :images)
    .where(categories: {name: "caphe"})
    .order(created_at: :DESC)
    .limit(8)
  end)

  scope :teas, (lambda do
    select(:id, :name, :price, "images.picture")
    .joins(:category, :images)
    .where(categories: {name: "trasua"})
    .order(created_at: :DESC)
    .limit(8)
  end)

  def self.searchs searchs
    if searchs
      if searchs[:pricefrom].present? && searchs[:priceto].present?
        results = self.search_price(searchs[:pricefrom], searchs[:priceto])
      elsif searchs[:priceto].present?
        result = self.search_to(searchs[:priceto])
      elsif searchs[:pricefrom].present?
        result = self.search_from(searchs[:pricefrom])
      elsif result.present?
        results = results.select_cate_product(searchs[:sltCategory]) if searchs[:sltCategory].present?
      elsif result.blank?
        results= self.select_cate_product(searchs[:sltCategory]) if searchs[:sltCategory].present?
      end
    else
      where(nil)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"

  before_action :load_product, except: [:index, :new, :create]

  def index
    @products = Product.includes(:images).order_by_name.paginate page: params[:page],
      per_page: Settings.products.paginate.per_page
  end

  def new
    @product = Product.new
    @image = @product.images.build
  end

  def create; end

  def edit; end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "flash.update_success"
    else
      flash[:danger] = t "flash.updated_fail"
    end
    redirect_to admin_listproducts_path
  end

  def destroy
    if @product.destroy
      flash[:success] = t "flash.product_delete_success"
    else
      flash[:danger] = t "flash.destroy_fail"
    end
    redirect_to admin_listproducts_path
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    @check_product = OrderDetail.find_by product_id: @product[:id]
    if @check_product
      if @check_product.order.finished?
        return @product
      else
        flash[:danger] = t "flash.product_delete_fail"
        redirect_to admin_listproducts_path
      end
    elsif @check_product.nil?
      return @product
    end
  end

  def product_params
    params.require(:product).permit :name, :price, :description,
      images_attributes: [:id, :product_id, :picture]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show

  def index
    @products = Product.includes(:images).paginate page: params[:page],
      per_page: Settings.products.paginate.per_page
    @q = Product.ransack(params[:q])
    @searchs = @q.result(distinct: true)
    @searchs = @searchs.select_cate_product(params[:sltCategory]) if params[:sltCategory]
    if session[:cart]
      @cart_products = Product.select_id_product session[:cart].keys
      return if @cart_products
    end
  end

  def show
    if @product
      respond_to do |format|
        format.html{return @product}
        format.js
      end
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t "flash.not_found"
    redirect_to root_path
  end

  def search_params
    params.permit :sltCategory, :priceto, :pricefrom
  end
end

app/views/products/_filter.html.erb
<div class="well">
  <h3 align="center"><%= t "products.filter.title" %></h3>
  <%= search_form_for @q, url: products_path, id: "search_form", class: "form-horizontal", method: :get do |f| %>
<!--   <form class="form-horizontal" method="get" id="search_form" action="/products" >
 -->
     <div class="form-group">
      <label for="location1" class="control-label"><%= t "products.filter.category" %></label>
      <select class="form-control" name="sltCategory" id="location1">
        <option value="3"><%= t "products.filter.cake" %></option>
        <option value="1"><%= t "products.filter.tea" %></option>
        <option value="2"><%= t "products.filter.coffee" %></option>
      </select>
    </div>
    <div class="form-group">
      <label for="pricefrom" class="control-label"><%= t "products.filter.min_price" %></label>
      <div class="input-group">
        <div class="input-group-addon" id="basic-addon1">$</div>
<!--         <input type="text" class="form-control" name="pricefrom" aria-describedby="basic-addon1">
 -->
         <%= f.search_field :price_gteq, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="priceto" class="control-label"><%= t "products.filter.max_price" %></label>
      <div class="input-group">
        <div class="input-group-addon" id="basic-addon2">$</div>
<!--         <input type="text" class="form-control" name="priceto" aria-describedby="basic-addon1">
 -->
        <%= f.search_field :price_lteq, class: "form-control" %>
      </div>
    </div>
    <p class="text-center"><button class="btn btn-danger glyphicon glyphicon-search" type="submit"></button></p>
<!--   </form>
 -->
  <% end %>
</div>

app/views/products/_product.html.erb
<% products.each do |product|%>
<div class="col-sm-3">
  <div class="single-item">
    <div class="single-item-header">
      <%= image_tag product.images[0].picture.url, alt: product.name, class: "style_image" %>
    </div>
    <div class="single-item-body">
      <p class="single-item-title"><%= product.name %></p>
      <p class="single-item-price">
        <span><%= product.price %></span>
      </p>
    </div>
    <div class="single-item-caption">
      <%= link_to carts_path(product_id: product.id), method: :POST, remote: true, class: "add-to-cart pull-left" do %>
       <i class="fa fa-shopping-cart"></i>
      <% end %>
      <a class="beta-btn primary" href=<%= product_path(id: product.id) %>><%= t "static_pages.home.details"%><i class="fa fa-chevron-right"></i></a>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<% end %>

app/views/products/index.html.erb
<div class="container">
  <div id="content" class="space-top-none">
    <div class="main-content">
      <div class="space60">&nbsp;</div>
      <div class="row">
        <div class="col-sm-12">
          <div class="beta-products-list">
            <h3><%= t "products.index.title" %></h3>
            <div class="row">
              <div class="col-md-3">
                <%= render "products/filter" %>
              </div>
              <div class="col-md-9">
                <% if @searchs %>
                  <%= render "products/product", products: @searchs %>
                <% else %>
                  <%= render "products/product", products: @products %>
                <% end %>
              </div>
                <%= will_paginate %>
            </div>
          </div> <!-- .beta-products-list -->
        </div>
      </div> <!-- end section with sidebar and main content -->
    </div> <!-- .main-content -->
  </div> <!-- #content -->
</div> <!-- .container -->

app/views/products/show.html.erb
<div class="container">
  <div id="content">
    <div class="row">
      <div class="col-sm-4">
        <%= image_tag @product.images[0].picture, alt: @product.name, class: "style_image" %>
      </div>
      <div class="col-sm-8">
        <div class="single-item-body">
          <p class="single-item-title"><%= @product.name %></p>
          <p class="single-item-price">
            <span><%= @product.price %></span>
          </p>
        </div>

        <div class="clearfix"></div>
        <div class="space20">&nbsp;</div>

        <div class="single-item-desc">
          <p><%= @product.description %></p>
        </div>
        <div class="space20">&nbsp;</div>

        <p>Options:</p>
        <div class="single-item-options">
          <%= form_tag carts_path(product_id: @product.id), remote: true ,method: :POST do %>
          <%= number_field_tag :quantity, t("products.show.one") %>
          <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-shopping-cart"></i></button>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <div class="space40">&nbsp;</div>
    <div class="woocommerce-tabs">
      <ul class="tabs">
        <li><%= t "products.show.description"%></li>
      </ul>
      <div class="panel">
        <p><%= @product.description %></p>
      </div>
      <div class="panel" id="tab-reviews">
        <p><%= t "products.show.review"%></p>
      </div>
    </div>
  </div>
</div>
<div class="space50">&nbsp;</div>